### ISSUE TITLE
仅设置setEndArg时,endArg为null

### ISSUE THREAD

**Issue by kwdassk** [easy-swoole/tracker#4]
问题：仅设置setEndArg时,endArg为null
        $point = PointContext::getInstance()->next('ControllerOnRequest');
        //假设这里进行了权限验证，并模拟数据库耗时
        $point->setEndArg([
            'uri'=>'2341241',
            'get'=>'123412341234'
        ]);
        $point->end();
解决办法：tracker/src/Point文件内，end方法复制时希望可以加下判断

    function end(string $status = self::END_SUCCESS,$arg = null)
    {
        if($this->status != self::END_UNKNOWN){
           return false;
        }
        $this->status = $status;
        $this->endArg = $arg ? $arg : $this->endArg;
        $this->endTime = round(microtime(true),4);
        return true;
    }

**Comment by kiss291323003** [comment]
感谢反馈，已经处理
